export const GET_CATEGORY = "GET_CATEGORY";
export const GET_SINGLE_CATEGORY = "GET_SINGLE_CATEGORY";
export const CREATE_QUESTION = "CREATE_QUESTION";
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";
